services:
  db:
    image: postgres:16
    container_name: postgres_portfolio
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py ensure_superadmin &&
             python manage.py ensure_site_defaults &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - media_data:/app/media
      - static_data:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
  media_data:
  static_data:
