from typing import Protocol


class RateLimiter(Protocol):
    def check(self, key: str, limit: int, seconds: int) -> bool: ...


class CounterStore(Protocol):
    def increment(self, namespace: str, dimensions: tuple[str, ...]) -> None: ...


class JsonCache(Protocol):
    def get(self, key: str) -> dict | None: ...
    def set(self, key: str, value: dict, ttl_seconds: int) -> None: ...
    def delete(self, *keys: str) -> None: ...


class SnapshotStorage(Protocol):
    def exists(self, name: str) -> bool: ...
    def read(self, name: str) -> dict: ...
    def write(self, name: str, payload: dict) -> None: ...
