import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Puck} from '@puckeditor/core';
import '@puckeditor/core/puck.css';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import createClient from 'openapi-fetch';
import {LayoutDashboard,Files,Image as ImageIcon,Settings,LogOut,ArrowUpRight,Plus} from 'lucide-react';
import {Renderer,config} from './renderer';
import './style.css';
import './builder.css';
import {editorOverrides} from './builder';
import {SectionsManager} from './sections';
const client=createClient({baseUrl:'',credentials:'same-origin'});
async function api(path,method='GET',body){const {data,error,response}=await client[method](path,{body});if(!response.ok)throw new Error(typeof error?.detail==='string'?error.detail:'No se ha podido completar la operación');return data;}
function App(){const [site,setSite]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/api/public/site').then(s=>{setSite(s);document.title=s.title;document.querySelector('meta[name="description"]').content=s.description}).catch(e=>setError(e.message))},[]);if(error)return <div className="loading">No se puede conectar con el servidor. {error}<br/><button onClick={()=>location.reload()}>Reintentar</button></div>;if(!site)return <div className="loading">Preparando tu portfolio…</div>;return location.pathname.startsWith('/admin')?<Admin site={site} setSite={setSite}/>:<Public site={site}/>}
function Public({site}){const [page,setPage]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/api/public/pages/'+(location.pathname.replace(/^\/|\/$/g,'')||'home')).then(setPage).catch(e=>setError(e.message))},[]);return <div className="public"><header className="public-header"><a href="/" className="brand">{site.name}<span>®</span></a><nav><a href="/#proyectos">Proyectos</a><a href="/#sobre-mi">Sobre mí</a><a className="nav-contact" href="/#contacto">Hablemos ↗</a></nav></header><main>{error?<div className="loading"><h1>{error}</h1><a href="/">Volver al inicio</a></div>:page?<Renderer data={page.content}/>:<div className="loading">Cargando…</div>}</main><footer><span>© {new Date().getFullYear()} {site.name}</span><span>Diseñado con intención.</span><a href="/admin">Administración ↗</a></footer></div>}
function Login({onLogin}){const [error,setError]=useState('');const {register,handleSubmit,formState:{isSubmitting,errors}}=useForm({resolver:zodResolver(z.object({username:z.string().min(1),password:z.string().min(1)})),defaultValues:{username:'superadmin'}});return <main className="login"><form onSubmit={handleSubmit(async values=>{try{await api('/api/auth/login','POST',values);onLogin()}catch(e){setError(e.message)}})}><span className="eyebrow">PORTFOLIO / STUDIO</span><h1>Tu espacio creativo.</h1><p>Entra para dar forma a tu próxima idea.</p><label>Usuario<input autoComplete="username" {...register('username')}/></label><label>Contraseña<input type="password" autoComplete="current-password" {...register('password')}/></label>{(error||Object.keys(errors).length>0)&&<p role="alert" className="error">{error||'Completa ambos campos'}</p>}<button className="primary" disabled={isSubmitting}>{isSubmitting?'Entrando…':'Entrar al backoffice ↗'}</button><a href="/">← Volver al portfolio</a></form></main>}
function Admin({site,setSite}){
 const [auth,setAuth]=useState(null),[tab,setTab]=useState('dashboard'),[pages,setPages]=useState([]),[assets,setAssets]=useState([]),[editing,setEditing]=useState(null),[draft,setDraft]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState(false);
 const refresh=async()=>{const [p,a]=await Promise.all([api('/api/pages'),api('/api/assets')]);setPages(p);setAssets(a)};
 useEffect(()=>{api('/api/auth/me').then(()=>setAuth(true)).catch(()=>setAuth(false))},[]);
 useEffect(()=>{if(auth)refresh().catch(e=>setMessage(e.message))},[auth]);
 async function action(fn){setBusy(true);setMessage('');try{await fn()}catch(e){setMessage(e.message)}finally{setBusy(false)}}
 async function save(publish=false,data=draft){await api('/api/pages/'+editing.id,'PATCH',{title:editing.title,slug:editing.slug,draft:data});if(publish)await api('/api/pages/'+editing.id+'/publish','POST');await refresh();setMessage(publish?'Publicado. Tu web ya está actualizada.':'Borrador guardado. La web pública no cambia.')}
 if(auth===null)return <div className="loading">Comprobando sesión…</div>;if(!auth)return <Login onLogin={()=>setAuth(true)}/>;
 if(editing)return <div className="editor"><div className="editor-toolbar"><button onClick={()=>{if(confirm('Salir del editor? Los cambios sin guardar se perderán.')){setEditing(null);setPreview(false)}}}>← Páginas</button><strong>{editing.title}</strong><button onClick={()=>setPreview(!preview)}>{preview?'Volver al editor':'Previsualizar'}</button><button disabled={busy} onClick={()=>action(()=>save())}>Guardar borrador</button><button className="primary" disabled={busy} onClick={()=>action(()=>save(true))}>Publicar ↗</button><span role="status">{message}</span></div>{preview?<div className="public"><Renderer data={draft}/></div>:<Puck overrides={editorOverrides} config={config} data={draft} onChange={setDraft} onPublish={data=>action(()=>save(false,data))} headerTitle={editing.title} dictionary={{'header-publish':'Guardar borrador'}} iframe={{enabled:true}}/>}</div>;
 return <div className="admin"><aside><a className="brand" href="/">studio<span>®</span></a><small>YOUR PORTFOLIO, YOUR RULES</small><nav>{[['dashboard','Resumen',LayoutDashboard],['pages','Páginas',Files],['sections','Secciones',Files],['media','Imágenes',ImageIcon],['settings','Configuración',Settings]].map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setMessage('')}}><Icon size={18}/>{label}</button>)}</nav><a href="/" target="_blank" rel="noreferrer">Ver portfolio <ArrowUpRight size={16}/></a><button onClick={()=>action(async()=>{await api('/api/auth/logout','POST');setAuth(false)})}><LogOut size={16}/> Cerrar sesión</button></aside><main className="admin-main"><header><span>ESPACIO DE TRABAJO / {tab.toUpperCase()}</span><span className="avatar">A</span></header><div className="admin-title"><div><span className="eyebrow">TU ESTUDIO DIGITAL</span><h1>{tab==='dashboard'?'Hola, vamos a crear.':tab==='pages'?'Tus páginas.':tab==='sections'?'Tus secciones.':tab==='media'?'Biblioteca visual.':'Los pequeños detalles.'}</h1><p>Un lugar para construir, editar y compartir tu trabajo.</p></div><a className="pill" href="/" target="_blank" rel="noreferrer">Ver web ↗</a></div>{message&&<p className="notice" role="status">{message}</p>}
 {tab==='dashboard'&&<><div className="stats"><div><small>PÁGINAS</small><strong>{pages.length}</strong></div><div><small>PUBLICADAS</small><strong>{pages.filter(p=>p.published).length}</strong></div><div><small>IMÁGENES</small><strong>{assets.length}</strong></div></div><div className="welcome"><span className="eyebrow">DE LA IDEA A LA PANTALLA</span><h2>Tu próxima gran idea<br/>empieza aquí.</h2><p>Edita tu portada y hazla tuya. Publica cuando estés listo.</p><button className="primary" onClick={()=>setTab('pages')}>Editar mi portfolio ↗</button><span className="welcome-star">✳</span></div><h3>Actividad reciente</h3>{pages.map(p=><div className="page-row" key={p.id}><strong>{p.title}</strong><span>Modificada {new Date(p.updated_at).toLocaleString('es')}</span><span>{p.published?'Publicada':'Borrador'}</span></div>)}</>}
 {tab==='pages'&&<><PageForm busy={busy} onSave={values=>action(async()=>{await api('/api/pages','POST',values);await refresh();setMessage('Página creada')})}/>{pages.map(p=><div className="page-card" key={p.id}><div><h3>{p.title}</h3><small>/{p.slug==='home'?'':p.slug} · {p.published?'Publicada':'Borrador'}</small></div><button onClick={()=>{setEditing(p);setDraft(p.draft);setMessage('')}}>Editar diseño ↗</button><button disabled={busy} onClick={()=>action(async()=>{await api('/api/pages/'+p.id+'/publish','POST');await refresh();setMessage('Página publicada')})}>Publicar borrador</button>{p.slug!=='home'&&<button disabled={busy} onClick={()=>{if(confirm('¿Eliminar esta página?'))action(async()=>{await api('/api/pages/'+p.id,'DELETE');await refresh()})}}>Eliminar</button>}</div>)}</>}
 {tab==='media'&&<><label className="upload">Subir una imagen <Plus/><small>JPG, PNG o WebP · hasta 10 MB · convertida a WebP</small><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files[0];if(!file)return;action(async()=>{const body=new FormData();body.append('file',file);const r=await fetch('/api/assets',{method:'POST',body});if(!r.ok)throw new Error('No se pudo subir la imagen (máximo 10 MB)');await refresh();setMessage('Imagen subida. Copia su URL en un bloque Image.');e.target.value=''})}}/></label><div className="media-grid">{assets.map(a=><div key={a.id}><img src={a.url} alt={a.filename}/><strong>{a.filename}</strong><input readOnly value={a.url} onFocus={e=>e.target.select()} aria-label="URL de imagen"/><button onClick={()=>action(async()=>{await navigator.clipboard.writeText(a.url);setMessage('URL copiada')})}>Copiar URL</button><button onClick={()=>{if(confirm('¿Eliminar imagen? Dejará de verse donde esté en uso.'))action(async()=>{await api('/api/assets/'+a.id,'DELETE');await refresh()})}}>Eliminar</button></div>)}</div>{assets.length===0&&<p>Aún no hay imágenes. Sube la primera para usarla en el editor.</p>}</>}
 {tab==='sections'&&<SectionsManager/>}
 {tab==='settings'&&<SettingsForm site={site} busy={busy} onSave={values=>action(async()=>{setSite(await api('/api/settings','PATCH',values));setMessage('Configuración actualizada en la web pública.')})}/>}
 </main></div>
}
function PageForm({onSave,busy}){const {register,handleSubmit,formState:{errors}}=useForm({resolver:zodResolver(z.object({title:z.string().min(1).max(100),slug:z.string().regex(/^[a-z0-9][a-z0-9-]{0,79}$/)}))});return <form className="inline-form" onSubmit={handleSubmit(onSave)}><input placeholder="Nombre de página" aria-label="Nombre" {...register('title')}/><input placeholder="slug-de-pagina" aria-label="Slug" {...register('slug')}/><button className="primary" disabled={busy}>Crear página +</button>{Object.keys(errors).length>0&&<small role="alert">Introduce un nombre y un slug con letras minúsculas, números o guiones.</small>}</form>}
function SettingsForm({site,onSave,busy}){const {register,handleSubmit,formState:{errors}}=useForm({defaultValues:site,resolver:zodResolver(z.object({name:z.string().min(1).max(100),profession:z.string().max(150),email:z.email().max(200),title:z.string().max(200),description:z.string().max(500)}))});return <form className="settings-form" onSubmit={handleSubmit(onSave)}>{[['name','Nombre'],['profession','Profesión'],['email','Email'],['title','Título SEO'],['description','Descripción SEO']].map(([key,label])=><label key={key}>{label}<input {...register(key)}/>{errors[key]&&<small className="error">{errors[key].message}</small>}</label>)}<p>Estos ajustes se aplican inmediatamente. Los textos de los bloques se editan en cada página.</p><button className="primary" disabled={busy}>Guardar configuración</button></form>}
createRoot(document.getElementById('root')).render(<App/>);
