import { describe, expect, it } from 'vitest';
import type { DocumentPayload } from './editor-types';
import { documentToPuckData, normalizePuckId, puckDataToDocument } from './puck-adapter';

describe('Puck document adapter', () => {
  it('round-trips nested nodes and normalizes identifiers generated by Puck', () => {
    const documentId = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
    const sectionId = '11111111-1111-4111-8111-111111111111';
    const headingId = '22222222-2222-4222-8222-222222222222';
    const document: DocumentPayload = {
      document: { id: documentId, name: 'Inicio', revision: 7 },
      page: { slug: '', title: 'Inicio', is_home: true, is_enabled: true },
      root_nodes: [sectionId],
      nodes: {
        [sectionId]: { id: sectionId, document_id: documentId, parent_id: null, node_type: 'SECTION', position: 10, props: {}, layout: {}, style_overrides: {}, classes: [] },
        [headingId]: { id: headingId, document_id: documentId, parent_id: sectionId, node_type: 'HEADING', position: 10, props: { text: 'Hola', tag: 'h1' }, layout: { columnSpan: { desktop: 8 } }, style_overrides: { desktop: { default: { color: '#111' } } }, classes: ['class-1'] },
      },
    };

    const data = documentToPuckData(document);
    const children = data.content[0].props.content;
    children[0].props.text = 'Actualizado';
    children.push({ type: 'TEXT', props: { id: 'TEXT-33333333-3333-4333-8333-333333333333', text: 'Nuevo', nodeProps: {}, propsJson: '{}', layoutJson: '{}', stylesJson: '{}', classes: [] } });

    const roundTrip = puckDataToDocument(data, document);
    const newId = '33333333-3333-4333-8333-333333333333';
    expect(roundTrip.nodes[headingId].props.text).toBe('Actualizado');
    expect(roundTrip.nodes[headingId].classes).toEqual(['class-1']);
    expect(roundTrip.nodes[headingId].style_overrides.desktop.default.color).toBe('#111');
    expect(roundTrip.nodes[newId].parent_id).toBe(sectionId);
    expect(roundTrip.root_nodes).toEqual([sectionId]);
    expect(normalizePuckId(`TEXT-${newId}`)).toBe(newId);
  });
});
